services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - database

  database:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204-slim
    volumes:
      - db-data:/data/db

volumes:
  db-data:
